version: '3.8'

services:
  product-catalog-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Persist H2 database data
      - ./data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s